import enum


class ConnectorType(str, enum.Enum):
    DIRECT_API = "DIRECT_API"
    ACCOUNT_AGGREGATOR = "ACCOUNT_AGGREGATOR"
    PROVIDER_API = "PROVIDER_API"
    IMPORT = "IMPORT"
    MANUAL = "MANUAL"


class ConnectorCapability(str, enum.Enum):
    HOLDINGS = "HOLDINGS"
    POSITIONS = "POSITIONS"
    TRANSACTIONS = "TRANSACTIONS"
    BALANCES = "BALANCES"
    ORDERS = "ORDERS"
    INVESTMENTS = "INVESTMENTS"
    REPAYMENTS = "REPAYMENTS"
    INTEREST = "INTEREST"
    OUTSTANDING = "OUTSTANDING"
    STATEMENTS = "STATEMENTS"
    ASSETS = "ASSETS"


class ConnectionMethodStatus(str, enum.Enum):
    AVAILABLE = "AVAILABLE"
    COMING_SOON = "COMING_SOON"
    PLANNED = "PLANNED"
    SANDBOX = "SANDBOX"


class ConnectionState(str, enum.Enum):
    AVAILABLE = "AVAILABLE"
    COMING_SOON = "COMING_SOON"
    CONNECTING = "CONNECTING"
    CONNECTED = "CONNECTED"
    SYNCING = "SYNCING"
    SYNCED = "SYNCED"
    SYNC_FAILED = "SYNC_FAILED"
    DISCONNECTED = "DISCONNECTED"
    IMPORT_ONLY = "IMPORT_ONLY"
    MANUAL = "MANUAL"
    SANDBOX = "SANDBOX"
